# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BtcP2q49uT9rW7sI3T2nb6Y1OtsJ3XXw
"""

config.py
API_KEY="Ciz23CSLeP1YNP88FWi975wkM3Je3jh1"